### ISSUE TITLE
time-varying scattering length

### ISSUE THREAD

**Issue by biswaroopmukherjee** [biswaroopmukherjee/condensate#15]
To make g time-varying, we can send an array of length steps to gpcore.Setup(). Then, in the loop, we can pass the timestep into Wavefunction::RealSpaceHalfStep() so that we can pass  gpcore::chamber.g[timestep] into realspaceKernelLauncher. 

We can also extend this to time-vary the cooling (and even dt, if we wanted to do some sophisticated adaptive timestepping at some point)

**Comment by Yaoruixiao** [comment]
A time varying scattering length, and thus time varying g has been added. To call Feshbach(a_s) one can set the time sequence for varying g. Note that Feshbach(a_s) should be called right before evolve(). i.e. no re-call harmonic-potential after Feshbach()
